services:
  adguard:
    image: "${IMAGE}"
    container_name: "adguard"
    restart: "always"
    networks:
      - "reverse-proxy"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./data:/opt/adguardhome/work"
      - "./config:/opt/adguardhome/conf"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home.tastic`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      - "diun.enable=true"
      - "diun.include_tags=^v\\d+\\.\\d+\\.\\d+$"
      - "homepage.group=Network & Security"
      - "homepage.name=Adguard"
      - "homepage.icon=adguard-home.png"
      - "homepage.href=https://adguard.home.tastic"
      - "homepage.description=DNS & Ad Blocker"
      - "homepage.widget.type=adguard"
      - "homepage.widget.url=https://adguard.home.tastic"
      - "homepage.widget.username=${ADGUARD_USERNAME}"
      - "homepage.widget.password=${ADGUARD_PASSWORD}"

networks:
  reverse-proxy:
    external: true
