services:
  adguard:
    image: "${IMAGE}"
    container_name: "adguard"
    restart: "always"
    networks:
      - "reverse-proxy"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:80/tcp"
    volumes:
      - "./data:/opt/adguardhome/work"
      - "./config:/opt/adguardhome/conf"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "diun.enable=true"
      - "diun.include_tags=^v\\d+\\.\\d+\\.\\d+$"

networks:
  reverse-proxy:
    external: true
